matrix:
  include:
    - language: go
      go: 1.8
      before_script:
        - go get github.com/golang/lint/golint
      script:
        - cd go
        - make
    - language: go
      go: 1.9
      before_script:
        - go get github.com/golang/lint/golint
      script:
        - cd go
        - make
    - language: go
      go: master
      before_script:
        - go get github.com/golang/lint/golint
      script:
        - cd go
        - make
    - compiler: clang
      os: osx
      script:
        - cd c
        - make
    - compiler: gcc
      os: linux
      script:
        - cd c
        - make
