matrix:
  include:
    - language: go
      go:
        - 1.8
        - 1.9
        - master
      before_script:
        - go get github.com/golang/lint/golint
      script:
        - cd go
        - make
